# Parallel computation with Ray

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/coobas/europython-25/blob/main/solutions/04-ray.ipynb)

[Ray](https://docs.ray.io/en/latest/index.html) is a set of libraries that (among others) allow an easy parallelisation of Python tasks - both locally and also in clusters. This part is called **Ray Core**.

Apart from this, it also provides specialised libraries for data processing (**Ray Data**), for machine learning and even reinforcement learning (**Ray Train**, **Ray Train**, ...). We will not deal with those in this workshop.

In [1]:
# Run this in Google Collab, not needed if you install this package locally
!pip install ray[default]

Defaulting to user installation because normal site-packages is not writeable


In [11]:
# Obligatory imports
import numpy as np
import pandas as pd
import ray
import plotly.express as px
from IPython import get_ipython

from pathlib import Path

In [12]:
is_colab = "google.colab" in str(get_ipython())

# Download the data which are part of this repo
if is_colab:
    import urllib
    url = "https://github.com/coobas/europython-25/raw/refs/heads/main/data.parquet"
    urllib.request.urlretrieve(url, "data.parquet")

In [13]:
def long_running(i: int) -> int:
    """A long running task that we will parallelise."""
    import time
    time.sleep(1)
    return i * i

In [14]:
%%time
long_running(1)

CPU times: user 1.69 ms, sys: 1.98 ms, total: 3.67 ms
Wall time: 1 s


1

In [15]:
%%time
[long_running(i) for i in range(10)]
    

CPU times: user 13.8 ms, sys: 7.78 ms, total: 21.6 ms
Wall time: 10 s


[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

If these tasks are independent, we can run them in parallel. There are of course options in Python itself:

- multiprocessing (https://docs.python.org/3.13/library/multiprocessing.html) 
- threading (with GIL-releasing code or with caution in free-threaded Python 3.13+)

This does scale exactly well if there are more tasks than CPUs / GPUs on your machine...

Other options:
- [celery](https://docs.celeryq.dev/en/stable/)
- [dask](https://docs.dask.org/en/stable/index.html)

With their strengths and weaknesses. 

## Use ray

Ray always runs a server (even implicitly) and executes the task in nodes that it manages.

In [16]:
ray.init()

RuntimeError: Maybe you called ray.init twice by accident? This error can be suppressed by passing in 'ignore_reinit_error=True' or by calling 'ray.shutdown()' prior to 'ray.init()'.

This either connects to an existing local server, or creates a new one. (In the same way, we can connect to a different one).

### Remote functions

Any function we decorate with the `ray.remote` decorator, becomes a **task** that can be submitted to this server.

In [17]:
@ray.remote
def long_running_ray(i: int) -> int:
    import time
    time.sleep(1)
    return i * i

In [18]:
long_running_ray(1)  # This will fail

TypeError: Remote functions cannot be called directly. Instead of running '__main__.long_running_ray()', try '__main__.long_running_ray.remote()'.

Well, the error message is right. We should use `.remote` (a different one!)

Better (and see that we pass arguments the same way):

In [19]:
%%time
long_running_ray.remote(1)

CPU times: user 26.6 ms, sys: 1.9 ms, total: 28.5 ms
Wall time: 28.4 ms


ObjectRef(c8ef45ccd0112571ffffffffffffffffffffffff0100000001000000)

What happened? The task was submitted to the cluster. But asynchronously. We have to capture the **future** object...

In [20]:
task_id = long_running_ray.remote(2)

...and get its value (synchronously):

In [21]:
ray.get(task_id)

4

In [ ]:
%%time
task_ids = [long_running_ray.remote(i) for i in range(10)]
ray.get(task_ids)

## Exercise: Compute k nearest neighbours remotely

We will reuse our definitions of kNN functions (slightly modified) and for random points fínd their neighbours:

In [22]:
DEFAULT_K = 4   # How many nearest neighbors to consider

def calculate_distances(query_points: np.ndarray, reference_points: np.ndarray, *, n_dim: int = 3) -> np.ndarray:
    """
    Calculate mutual Euclidean distances between M query and N reference points.

    Parameters:
    ----------
    query_points: np.ndarray
        (M, n_dim+) array of query points
    reference_points: np.ndarray
        (N, n_dim+) array of reference points
    n_dim: int
        Number of dimensions to consider (default: 3, for x, y, floor)

    Returns:
    --------
    distances: np.ndarray
        (M, N) array of the distances
    """
    # Expand for broadcasting
    query_points = query_points[:, np.newaxis,:n_dim]
    reference_points = reference_points[np.newaxis, :, :n_dim]
    return np.sqrt(np.sum((reference_points - query_points) ** 2, axis=-1))


def knn_search(
    query_points: np.ndarray,
    reference_points: np.ndarray,
    k: int,
):
    """
    Find k nearest neighbour reference point indices for N query points.

    Returns:
    --------
    indices: np.ndarray
        (N, k) matrix of integral indices
    """
    distances = calculate_distances(query_points, reference_points).T
    return np.argpartition(distances, k, axis=0)[:k].T

Let's create some points to test this on:

In [23]:
def create_random_points(
    n_points: int, *, n_dim: int = 3, seed: int = 42
) -> np.ndarray:
    # TODO: Fix floor!
    np.random.seed(seed)
    return np.random.sample((n_points, n_dim))

In [25]:
query_points = create_random_points(5, seed=42)
reference_points = create_random_points(10, seed=84)

query_points

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452],
       [0.05808361, 0.86617615, 0.60111501],
       [0.70807258, 0.02058449, 0.96990985],
       [0.83244264, 0.21233911, 0.18182497]])

In [24]:
calculate_distances(query_points, reference_points)

NameError: name 'query_points' is not defined

First, we run this without ray (for sizable arrays):

In [26]:
%%time
query_points = create_random_points(32768, seed=42)
reference_points = create_random_points(1000, seed=84)
knn_search(query_points, reference_points, k=DEFAULT_K)

CPU times: user 1.57 s, sys: 98.6 ms, total: 1.67 s
Wall time: 1.68 s


array([[532, 606, 302, 371],
       [271, 552, 872, 544],
       [520, 125, 178, 885],
       ...,
       [820, 102, 966, 620],
       [339, 990, 107, 114],
       [847, 267,  66, 724]], shape=(32768, 4))

**Task**

1. Change the knn_search function into a task.
2. Submit the computation to ray and compare the results.
3. Look at the execution times (and compare to local run)

In [ ]:
@ray.remote
def knn_search_ray(
    query_points: np.ndarray,
    reference_points: np.ndarray,
    k: int,
):
    """
    Find k nearest neighbour reference point indices for N query points.

    Returns:
    --------
    indices: np.ndarray
        (N, k) matrix of integral indices
    """
    distances = calculate_distances(query_points, reference_points).T
    return np.argpartition(distances, k, axis=0)[:k].T

In [ ]:
%%time
knn_id = knn_search_ray.remote(query_points, reference_points, k=DEFAULT_K)
knn_results = ray.get(knn_id)

**Question:** Is there any improvement yet?

## Monitoring ray

Ray comes with a nice dashboard that allows you to observe running jobs. It runs in a local web server, mostly likely http://localhost:8265. This address is not accessible when running within Google Colab, and so you have to use a special trick to show a mini-window forwarded to the dashboard running in the cloud.

In [ ]:
is_colab = "google.colab" in str(get_ipython())

if is_colab:
    from google.colab import output
    output.serve_kernel_port_as_iframe(8265)  # The port may differ!
else:
    print("Not in google Colab. Try the local link, it should work.")

Now we submit something really huge:

In [ ]:
query_points = create_random_points(10000000, seed=42)
reference_points = create_random_points(100, seed=84)
task_id = knn_search_ray.remote(query_points, reference_points, k=DEFAULT_K)


In [ ]:
%%time
ray.get(task_id)

## Exercise: Parallelize kNN execution

Ray by itself does not do any optimisations or segments the tasks you send it. So you need to care about splitting the task yourself. Sometimes this is easy, sometimes it requires a deeper thought (or a library ;-)).

If you want to improve the computation of nearest neighbours for a bunch of **independent** points, this is really easy ("embarassingly parallel problem). Just take the 1000000 query points and split them into **batches**:

In [27]:
def split_into_batches(array: np.ndarray, max_size: int) -> list[np.ndarray]:
    """
    Split an array into smaller batches of a maximum size.

    Parameters:
    ----------
    array: np.ndarray
        The array to split.
    max_size: int
        The maximum size of each batch.

    Returns:
    --------
    list[np.ndarray]
        A list of arrays, each with a maximum size of `max_size`.
    """
    return [array[i:i + max_size] for i in range(0, len(array), max_size)]

In [ ]:
split_into_batches(np.arange(10), 3)

**Task**: 
1. Split the query points accordingly (you may experiment with batch_size, 1000 is pretty ok)
2. Submit and retrieve the results for the batches
3. Combine the results back into one array ([np.vstack](https://numpy.org/doc/stable/reference/generated/numpy.vstack.html) is your friend)

In [ ]:
query_points = create_random_points(10000000, seed=42)
reference_points = create_random_points(100, seed=84)

batches = split_into_batches(query_points, 1000)
batches

In [ ]:
%%time
task_ids = [
    knn_search_ray.remote(batch, reference_points, k=DEFAULT_K) for batch in batches
]
knn_results = ray.get(task_ids)
knn_results

In [ ]:
np.vstack(knn_results)

**Question** Can we parallelise in the reference points dimension?

## Example: Predicting the housing prices with a database of reference points

We can use the distances to predict the housing prices (in arbitrary units, perhaps the monthly rent in $ for a single-bedroom apartment?) based on our custom regression implementation. 

In [28]:
def compute_prices(query_points, reference_points, k: int = DEFAULT_K):
    """
    Find prices for N data_points.

    Parameters:
    query_points: np.ndarray
        (N, 3) array of query points
    reference_points: np.ndarray
        (M, 4) array of data points with x, y, floor, and price
    k: int
        Number of nearest neighbors to consider

    Returns:
    --------
    prices: np.ndarray
        (N,) array of prices
    """
    indices = knn_search(query_points, reference_points, k)
    prices: np.ndarray = reference_points[indices, 3]
    return prices.mean(axis=1)


We have predefined reference points in an external file, modeled using an (unknown?) analytical function:

In [ ]:
is_colab = "google.colab" in str(get_ipython())

# Download the data which are part of this repo
if is_colab:
    import urllib
    url = "https://github.com/coobas/europython-25/raw/refs/heads/main/data.parquet"
    urllib.request.urlretrieve(url, "data.parquet")
    print("Data downloaded to data.parquet.")
else:
    print("Not in Google Colab, skipping data download.")

In [29]:
def load_reference_points_df(path: Path = Path("../data.parquet")) -> np.ndarray:
    """
    Load reference data points from a parquet file.

    Returns:
    --------
    data_points: np.ndarray
        (N, 4) array of data points with x, y, floor, and price columns
    """

    return pd.read_parquet(path)
    # return df[["x", "y", "floor", "price"]].to_numpy().astype(float)

reference_points_df = load_reference_points_df()
reference_points_df

x         y  floor        price
0    -2.509198 -2.527184      1   983.737837
1     9.014286 -3.341758      3   520.453425
2     4.639879 -6.476922     12   621.498431
3     1.973170  2.145333     12  1751.234358
4    -6.879627 -0.467517     16   672.690047
...        ...       ...    ...          ...
9995  7.153120  7.540773      3   520.173028
9996  7.950177 -9.063721      3   520.453522
9997  8.934158 -3.926031     16   673.260987
9998 -2.050240 -1.133600      1  1325.611747
9999 -5.657192 -6.554704     14   646.913957

[10000 rows x 4 columns]

And we also want to run something against this. Let's start with random points:

In [30]:
def create_random_3d_points(
        n_points: int = 100, *, ranges: list[tuple[float, float]] = [(-10, 10), (-10, 10), (1, 20)], ) -> np.ndarray:
    """
    Create random 3D points within specified ranges.

    Parameters:
    ----------
    n_points: int
        Number of points to generate.    
    ranges: list[tuple[float, float]]
        List of tuples specifying the range for each dimension.


    Returns:
    --------
    points: np.ndarray
        (n_points, len(ranges)) array of random points.
    """
    if not ranges or len(ranges) != 3:
        raise ValueError("Ranges must be a list of three tuples for x, y, and floor dimensions.")
    df = np.random.uniform(
        low=[r[0] for r in ranges],
        high=[r[1] for r in ranges],
        size=(n_points, len(ranges))
    )
    df[:, 2] = df[:, 2].astype(int)  # Ensure the floor is an integer
    return df

query_points = create_random_3d_points()
query_points

array([[-4.58733654,  8.41607641, 17.        ],
       [ 3.74643276, -7.22572255, 15.        ],
       [-2.14036507,  1.09481508, 18.        ],
       [ 4.0533283 ,  2.7300244 , 10.        ],
       [-4.24262995, -4.75579104,  6.        ],
       [-4.78100895, -6.49377754, 15.        ],
       [-4.41257889,  1.35382663,  6.        ],
       [ 1.66507327, -4.70075815,  5.        ],
       [ 9.3244321 ,  5.15729383, 13.        ],
       [ 1.15120558, -0.54369229, 17.        ],
       [-4.88242204,  8.77821153, 11.        ],
       [ 5.82075014,  9.37918177, 18.        ],
       [ 8.87804357, -5.15921442, 10.        ],
       [-2.29330358, -3.86109528, 15.        ],
       [-8.07298018,  4.49233142,  7.        ],
       [ 2.76832987,  7.29164771, 15.        ],
       [-1.11923795, -4.84902064,  3.        ],
       [ 9.70916004, -9.7192668 ,  5.        ],
       [ 3.47764399,  9.20511543, 16.        ],
       [-3.74296151,  6.39198537, 10.        ],
       [ 9.05752068, -0.30257105,  3.   

Our query points need to live in the same dimension (i.e. x,y between -10 and 10, floor between 1 and 20). Note that the floor distibution probably is not "uniform", but for demonstration purposes, it should not matter that much.

Let's see how the whole thing looks without ray:

In [34]:
prices = compute_prices(query_points, reference_points_df.to_numpy(), k=DEFAULT_K)
prices

array([ 686.44695276,  669.22860565, 1998.32335584, 1322.72351069,
        557.45894749,  659.78175268,  585.0934468 , 1530.06942809,
        637.31870009, 2530.695501  ,  609.5603613 ,  699.95208497,
        600.51269649, 1076.53978255,  562.98149036,  659.73703114,
        898.73516043,  541.27539212,  673.04914706,  597.64827466,
        522.82919186,  714.54249459,  588.60622981, 1548.41028468,
        637.29328336,  582.87338273,  541.28975894,  517.65718187,
        700.09487413, 2067.80720814, 1479.76171179,  509.94821624,
        669.52392544,  585.8892699 ,  631.09973196, 1920.15135273,
       1442.23041114,  549.38755315,  691.31543722, 1025.25381979,
       1752.89525215,  618.64701215,  689.7435575 , 1429.71398818,
        500.06785043,  551.98817403,  597.62698711,  520.24233612,
        588.82739055, 1186.02020719,  565.79991178,  563.19088851,
        563.10260533,  574.41713557, 1257.32730012,  530.53992897,
        693.33778602,  585.90597449, 1488.14221272,  634.06216

In [33]:
def combine_points_and_prices(
    query_points: np.ndarray, prices: np.ndarray
) -> pd.DataFrame:
    """
    Prepare human-friendly output from numpy arrays.

    Parameters:
    ----------
    query_points: np.ndarray
        (N, 3) array of query points
    prices: np.ndarray
        (N,) array of prices

    Returns:
    --------
    df: pd.DataFrame
        DataFrame with columns x, y, floor, price
    """
    return pd.DataFrame(
        {
            "x": query_points[:,0],
            "y": query_points[:,1],
            "floor": query_points[:,2].astype(int),
        }
    )

In [35]:
combine_points_and_prices(query_points, prices)

x         y  floor
0  -4.587337  8.416076     17
1   3.746433 -7.225723     15
2  -2.140365  1.094815     18
3   4.053328  2.730024     10
4  -4.242630 -4.755791      6
..       ...       ...    ...
95  4.295030 -8.533454      9
96  7.477883  9.350826     13
97 -1.321328 -4.441046     17
98 -1.121153 -3.382152      5
99  4.352642  3.150078      3

[100 rows x 3 columns]

We already know how to parallelise this:

In [36]:
# Note we can apply the decorator directly to the function
compute_prices_ray = ray.remote(compute_prices)

In [ ]:
%%time
query_points = create_random_3d_points(100_000)
batches = split_into_batches(query_points, 1_000)
task_ids = [
    compute_prices_ray.remote(batch, reference_points_df.to_numpy(), k=DEFAULT_K) 
    for batch in batches
]
np.hstack(ray.get(task_ids))

This is relatively fine but mind that we are passing the same reference points over and over again to ray (which requires repeated serialisation, ...). It does not matter that much in our case but if the reference points dataframe were larger, we might see a significant performance penalty.

### Storing objects in ray

What we can do instead, is to pass the object to ray just once and pass its **object id**. Ray automatically cares about using the referenced value.

Let's take it to the extreme and compute the price for each of 10,000 points in a separate task:

In [ ]:
%%time
query_points = create_random_3d_points(10_000)
batches = split_into_batches(query_points, 1_000)
task_ids = [
    compute_prices_ray.remote(batch, reference_points_df.to_numpy(), k=DEFAULT_K) 
    for batch in batches
]
ray.get(task_ids);

In [ ]:
%%time
query_points = create_random_3d_points(10_000)
batches = split_into_batches(query_points, 1)
task_ids = [
    compute_prices_ray.remote(batch, reference_points_df.to_numpy(), k=DEFAULT_K) 
    for batch in batches
]
ray.get(task_ids);

Do you see the degraded performance?

Of course it is mostly due to creating a task per point but part of the penalty is coming from passing the array so many times.

Putting objects into a ray cluster is very simple, actually:

In [ ]:
i = 9
arg_id = ray.put(i)
arg_id

In [ ]:
ray.get(long_running_ray.remote(arg_id))

**Task**

1. Modify the `compute_prices_ray` from above so that `reference_points_df.to_numpy()` is stored in the ray cluster and reused in each task.
2. Compare the execution time.

In [ ]:
%%time
query_points = create_random_3d_points(10000)
batches = split_into_batches(query_points, 1)
reference_id = ray.put(reference_points_df.to_numpy())
task_ids = [
    compute_prices_ray.remote(batch, reference_id, k=DEFAULT_K) 
    for batch in batches
]
ray.get(task_ids);

Is it better now?

**Question**: Would putting query points (either whole or batched) to ray help as well?

## TODO: Optional: Actors

We would like to create a map of prices, i.e. sample data in a grid over the allowed area and use our kNN model to predict a price for each of those (given the floor as a parameter). 

In [40]:
class PriceMap:
    DEFAULT_POINTS_PER_DIM = 21
    DEFAULT_LIMIT = 10.0

    points_per_dim: int
    limit: float
    floor: int

    query_points: np.ndarray

    def __init__(
        self,
        reference_points: np.ndarray,
        points_per_dim: int = DEFAULT_POINTS_PER_DIM,
        floor: int = 1,
        limit: float = DEFAULT_LIMIT,
    ):
        self.points_per_dim = points_per_dim
        self.reference_points = reference_points
        self.floor = floor
        self.limit = limit
        self._create_query_points()

    def _create_query_points(self) -> np.ndarray:
        """
        Create a homogenous grid of points with a floor to create a map.

        Returns:
        --------
        query_points: np.ndarray
            (n_points x n_points, 3) array of query points
        """
        x = np.linspace(-self.limit, self.limit, self.points_per_dim)
        y = np.linspace(-self.limit, self.limit, self.points_per_dim)
        x, y = (arr.flatten() for arr in np.meshgrid(x, y))
        self.query_points = np.vstack([x, y, np.ones(x.shape[0]) * self.floor]).T

    def compute_prices(self) -> np.ndarray:
        return compute_prices(self.query_points, self.reference_points, k=DEFAULT_K)

In [41]:
price_map = PriceMap(reference_points_df.to_numpy(), points_per_dim=10, floor=1)
price_map.compute_prices()

array([ 502.62571959,  495.10341566,  500.08443712,  502.40907427,
        500.03661855,  507.47369674,  500.02074848,  497.59564911,
        497.49921835,  502.54348979,  497.44893985,  497.58921302,
        497.55507817,  502.60535371,  497.64007895,  497.46649233,
        500.10013491,  497.55388254,  500.01996648,  502.59657281,
        500.09682999,  495.03729668,  495.06522865,  516.69827692,
        829.9530909 ,  971.00173282,  694.15259394,  502.61249975,
        499.94960905,  502.55920568,  502.65341359,  499.88948164,
        499.9896255 ,  678.16758431, 1376.8727563 , 1615.59885139,
       1242.70934716,  607.62934693,  497.54972248,  504.89269373,
        497.6841445 ,  505.11672521,  497.46523006,  863.30632403,
       1483.997877  , 1715.3985825 , 1241.6947183 ,  519.76844346,
        500.00961586,  497.5518391 ,  500.06356972,  499.95023628,
        500.02303676,  798.79329671, 1643.64638986, 1662.70738472,
       1333.3549859 ,  688.79540446,  500.02268248,  495.09228

TODO: Create an actor?

In [ ]:
def draw_points(points: np.ndarray) -> None:
    """
    Draw points on a map.

    Parameters:
    -----------
    points: np.ndarray
        (N, 3) array of points to draw
    """
    df = pd.DataFrame({"x": points[:,0], "y": points[:,1]})
    fig = px.scatter(df, x="x", y="y", title="Query points")
    fig.show()

draw_points(create_query_points(5))